import Button from '@/components/Button'
import Input from '@/components/Input'
import fetchData from '@/hooks/fetchData'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react';
import QRCode from "react-qr-code";
import { IoMdDownload } from "react-icons/io";


export default function Login() {

  const [user, setUser] = useState({ });

  const router = useRouter();
  useEffect(() => {
    (async() => {
      const { user } = await fetchData('/api/user');
      if(user) localStorage.setItem('luvo_driver', JSON.stringify(user));
      setUser(user);
    })();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-neutral-50 flex flex-col items-center place-content-center gap-8 p-4">


          <div className='relative w-11/12'>

            <svg id="blob-scene-haikei" xmlns="http://www.w3.org/2000/svg" width="1014" height="1014" viewBox="0 0 1014 1014">
              <rect id="Rectangle_1" data-name="Rectangle 1" width="1014" height="1014" fill="#34d399"/>
              <g id="Group_5" data-name="Group 5" transform="translate(619.667)">
                <path id="Path_6" data-name="Path 6" d="M44.333,394.333c-86.3-.225-172.718-.563-197.167-52.841S-139.989,185-162.523,119.427-267.528,26.927-350,0H44.333Z" transform="translate(350)" fill="#9333ea"/>
              </g>
              <g id="Group_6" data-name="Group 6" transform="translate(0 619.667)">
                <path id="Path_7" data-name="Path 7" d="M0-350c22.759,89.683,45.4,179.478,111.54,201.11s175.647-24.787,229.953-3.943c54.418,20.843,53.629,108.949,52.841,197.167H0Z" transform="translate(0 350)" fill="#9333ea"/>
              </g>
            </svg>

            <div className='absolute w-full h-full inset-0 flex flex-col justify-center items-center text-white space-y-2'>

              <div className='space-y-2'>
                <p className='font-bold text-4xl text-center font-[Teko] text-white'>luvo</p>
              </div>
              <div className='inline-block p-2 rounded-md'>
                <QRCode 
                  className="mx-auto" 
                  size={125} 
                  value={user?.tag} 
                />
              </div>
              <p className='text-lg text-center font-bold'>{user?.tag}</p>
              <p className='text-sm text-center font-bold'>{user?.company}</p>

            </div>

          </div>

          <div className='inline-flex gap-2 place-items-center font-bold bg-green-500 py-1 px-4 rounded-full mt-8'>
            <IoMdDownload className=" text-white" />
            <span className='text-xs text-white'>Download</span>
          </div>
        
      </main>
    </>
  )
}
