import Navbar from '@/components/Navbar';
import Transaction from '@/components/Transaction'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router';
import { useEffect, useLayoutEffect, useState } from 'react'
import { MdExitToApp } from 'react-icons/md';
import fetchData from '../hooks/fetchData';


export default function Dashboard() {

  const router = useRouter();
  const [data, setData] = useState({  });

  useLayoutEffect(() => {
    setData(JSON.parse(localStorage.getItem('luvo_dashboard_data') || "{}"));
  }, []);

  useEffect(() => {
    (async() => {
      const data = await fetchData('/api/transactions');
      if(data.status === 0){
        return router.push('/login');
      }

      localStorage.setItem('luvo_dashboard_data', JSON.stringify(data));
      setData(data);
    })();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="max-w-md mx-auto h-screen flex flex-col p-4 gap-4 bg-neutral-50 isolate">


        <Navbar 
          text={`Hi, ${data?.user?.tag.replace('@','')}`}
          noBack
        />

        
        <div className='space-y-5'>

          <div className='relative z-[1] bg-gradient-to-tr from-green-400 to-green-400 text-white p-8 rounded-xl space-y-2'>
            <p className='text-4xl font-bold'>&#8358;{(data?.user?.balance || 0).toLocaleString()}</p>
            <p className='text-xs text-neutral-200'>*Account Balance</p>
          </div>


          <div className='relative z-0 !-mt-4 w-11/12 mx-auto pt-8 grid grid-cols-3 bg-white p-4 rounded-lg border border-neutral-200'>

            <Link href="/profile">
              <div className='flex flex-col justify-center items-center p-2 space-y-2 active:bg-neutral-200 rounded-md'>
                <svg className='w-9 h-9' xmlns="http://www.w3.org/2000/svg" width="509" height="571.001" viewBox="0 0 509 571.001">
                  <g id="Group_1" data-name="Group 1" transform="translate(-239 -315.999)">
                    <circle id="Ellipse_1" data-name="Ellipse 1" cx="173.5" cy="173.5" r="173.5" transform="translate(401 540)" fill="#34d399"/>
                    <path id="Path_2" data-name="Path 2" d="M332.64,64.58C313.18,43.57,286,32,256,32c-30.16,0-57.43,11.5-76.8,32.38-19.58,21.11-29.12,49.8-26.88,80.78C156.76,206.28,203.27,256,256,256s99.16-49.71,103.67-110.82c2.27-30.7-7.33-59.33-27.03-80.6ZM432,480H80a31,31,0,0,1-24.2-11.13c-6.5-7.77-9.12-18.38-7.18-29.11C57.06,392.94,83.4,353.61,124.8,326c36.78-24.51,83.37-38,131.2-38s94.42,13.5,131.2,38c41.4,27.6,67.74,66.93,76.18,113.75,1.94,10.73-.68,21.34-7.18,29.11A31,31,0,0,1,432,480Z" transform="translate(191.006 283.999)" fill="#9333ea" stroke="#000" stroke-width="0"/>
                  </g>/
                </svg>
                <p className='font-bold text-xs text-center text-neutral-400'>Profile</p>
              </div>
            </Link>

            <Link href="/withdraw">
              <div className='flex flex-col justify-center items-center p-2 space-y-2 active:bg-neutral-200 rounded-md'>
                <svg className='w-9 h-9' xmlns="http://www.w3.org/2000/svg" width="504.01" height="382" viewBox="0 0 504.01 382">
                  <g id="Group_1" data-name="Group 1" transform="translate(-243.99 -505)">
                    <circle id="Ellipse_1" data-name="Ellipse 1" cx="173.5" cy="173.5" r="173.5" transform="translate(401 540)" fill="#34d399"/>
                    <path id="Path_3" data-name="Path 3" d="M402.371,46.549C377.243,36.01,352.1,32,326.963,32,247.177,31.994,167.4,72.382,87.611,72.382A196.54,196.54,0,0,1,27.6,63.495a22.149,22.149,0,0,0-6.7-1.049A20.612,20.612,0,0,0,0,83.051V288.563c0,8.181,4.683,15.935,12.2,19.083C37.331,318.193,62.478,322.2,87.611,322.2c79.786,0,159.572-40.389,239.359-40.389a196.54,196.54,0,0,1,60.016,8.887,22.149,22.149,0,0,0,6.7,1.049,20.612,20.612,0,0,0,20.891-20.606V65.639c-.006-8.188-4.69-15.935-12.211-19.09ZM31.093,96.92c13.033,3.265,26.636,4.9,40.628,5.785a41.506,41.506,0,0,1-40.628,33.386Zm0,184.615V250.584a41.444,41.444,0,0,1,41.27,39.773A156.489,156.489,0,0,1,31.093,281.535Zm176.194-42.248c-28.625,0-51.822-27.848-51.822-62.186s23.2-62.186,51.822-62.186,51.822,27.841,51.822,62.186S235.9,239.287,207.287,239.287Zm176.194,18a222.717,222.717,0,0,0-35.187-5.467,41.37,41.37,0,0,1,35.187-31.922Zm0-152.946a41.374,41.374,0,0,1-36.152-39.87,155.713,155.713,0,0,1,36.152,8.2Z" transform="translate(243.99 473)" fill="#9333ea" stroke="#000" stroke-width="0"/>
                  </g>
                </svg>
                <p className='font-bold text-xs text-center text-neutral-400'>Withdraw</p>
              </div>
            </Link>


          </div>

          <div className='py-2 space-y-2 pb-12'>

            <p className='font-bold'>History</p>

            {data?.data?.map(transaction => (
              <Transaction 
                key={transaction._id} 
                {...transaction}
              />
            ))}


          </div>

        </div>

        {/* <div className='bg-gradient-to-tr from-green-400 to-emerald-400 fixed grid place-content-center rounded-full w-12 h-12 shadow-2xl bottom-5 right-5'>
          <BiQrScan
            className="text-2xl font-bold text-white"
          />
        </div> */}

        
      </main>
    </>
  )
}
