import Navbar from '@/components/Navbar';
import Transaction from '@/components/Transaction'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router';
import { useEffect, useLayoutEffect, useState } from 'react'
import { MdExitToApp } from 'react-icons/md';
import fetchData from '../hooks/fetchData';


export default function Dashboard() {

  const router = useRouter();
  const [data, setData] = useState({  });

  useLayoutEffect(() => {
    setData(JSON.parse(localStorage.getItem('luvo_dashboard_data') || "{}"));
  }, []);

  useEffect(() => {
    (async() => {
      const data = await fetchData('/api/transactions');
      if(data.status === 0){
        return router.push('/login');
      }

      localStorage.setItem('luvo_dashboard_data', JSON.stringify(data));
      setData(data);
    })();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="max-w-md mx-auto h-screen flex flex-col p-4 gap-4 bg-neutral-50 isolate">


        <Navbar 
          text={`Hi, ${data?.user?.tag.replace('@','')}`}
          noBack
        />

        
        <div className='space-y-5'>

          <div className='relative z-[1] bg-gradient-to-tr from-green-400 to-green-400 text-white p-8 rounded-xl space-y-2'>
            <p className='text-4xl font-bold'>&#8358;{(data?.user?.balance || 0).toLocaleString()}</p>
            <p className='text-xs text-neutral-200'>*Account Balance</p>
          </div>


          <div className='relative z-0 !-mt-4 w-11/12 mx-auto pt-8 grid grid-cols-3 bg-white p-4 rounded-lg border border-neutral-200'>

            <Link href="/profile">
              <div className='flex flex-col justify-center items-center p-2 space-y-2 active:bg-neutral-200 rounded-md'>
                <svg className='w-9 h-9' xmlns="http://www.w3.org/2000/svg" width="509" height="571.001" viewBox="0 0 509 571.001">
                  <g id="Group_1" data-name="Group 1" transform="translate(-239 -315.999)">
                    <circle id="Ellipse_1" data-name="Ellipse 1" cx="173.5" cy="173.5" r="173.5" transform="translate(401 540)" fill="#34d399"/>
                    <path id="Path_2" data-name="Path 2" d="M332.64,64.58C313.18,43.57,286,32,256,32c-30.16,0-57.43,11.5-76.8,32.38-19.58,21.11-29.12,49.8-26.88,80.78C156.76,206.28,203.27,256,256,256s99.16-49.71,103.67-110.82c2.27-30.7-7.33-59.33-27.03-80.6ZM432,480H80a31,31,0,0,1-24.2-11.13c-6.5-7.77-9.12-18.38-7.18-29.11C57.06,392.94,83.4,353.61,124.8,326c36.78-24.51,83.37-38,131.2-38s94.42,13.5,131.2,38c41.4,27.6,67.74,66.93,76.18,113.75,1.94,10.73-.68,21.34-7.18,29.11A31,31,0,0,1,432,480Z" transform="translate(191.006 283.999)" fill="#34d399" stroke="#000" stroke-width="0"/>
                  </g>/
                </svg>
                <p className='font-bold text-xs text-center text-neutral-400'>Profile</p>
              </div>
            </Link>

            <Link href="/withdraw">
              <div className='flex flex-col justify-center items-center p-2 space-y-2 active:bg-neutral-200 rounded-md'>
                <svg className='w-9 h-9' xmlns="http://www.w3.org/2000/svg" width="384.667" height="394.833" viewBox="0 0 384.667 394.833">
                  <g id="Group_3" data-name="Group 3" transform="translate(-1496.353 -457.167)">
                    <circle id="Ellipse_1" data-name="Ellipse 1" cx="148" cy="148" r="148" transform="translate(1585.02 556)" fill="#9333ea"/>
                    <g id="Group_1" data-name="Group 1" transform="translate(1494.353 455.167)">
                      <path id="Path_2" data-name="Path 2" d="M64.445,133c-25.965,0-28.223-12.136-28.223-14.111H8c0,12.982,9.313,35.984,42.334,41.205v15.24H78.557V160.1c28.223-4.8,42.334-23,42.334-41.205,0-15.8-7.338-42.334-56.445-42.334-28.223,0-28.223-8.89-28.223-14.111S46.1,48.334,64.445,48.334,84.06,57.365,84.2,62.445h28.223A42.334,42.334,0,0,0,78.557,21.8V6H50.334V21.381C22.111,26.038,8,44.242,8,62.445c0,15.8,7.338,42.334,56.445,42.334,28.223,0,28.223,9.6,28.223,14.111S83.919,133,64.445,133Z" transform="translate(78.668 52.445)" fill="#34d399" stroke="#000" stroke-width="0"/>
                      <path id="Path_3" data-name="Path 3" d="M44.334,2H2V30.223H30.223V270.116a14.111,14.111,0,0,0,14.111,14.111H241.893A14.111,14.111,0,0,0,256,270.116V30.223h28.223V2ZM227.782,256H58.445V30.223H227.782Z" transform="translate(0 0)" fill="#34d399" stroke="#000" stroke-width="0"/>
                    </g>
                  </g>
                </svg>
                <p className='font-bold text-xs text-center text-neutral-400'>Withdraw</p>
              </div>
            </Link>

            <Link href="/banner">
              <div className='flex flex-col justify-center items-center p-2 space-y-2 active:bg-neutral-200 rounded-md'>
                <svg className='w-9 h-9' xmlns="http://www.w3.org/2000/svg" width="434.279" height="434.818" viewBox="0 0 434.279 434.818">
                  <g id="Group_4" data-name="Group 4" transform="translate(-925.02 -395.182)">
                    <circle id="Ellipse_1" data-name="Ellipse 1" cx="173.5" cy="173.5" r="173.5" transform="translate(925.02 483)" fill="#9333ea"/>
                    <g id="Group_2" data-name="Group 2" transform="translate(992 395.182)">
                      <path id="Path_4" data-name="Path 4" d="M0,0H367.3V367.3H0Z" fill="none" stroke="#000" stroke-width="0"/>
                      <path id="Path_5" data-name="Path 5" d="M277.474,33.608H32.608V247.866L174.814,105.629a15.3,15.3,0,0,1,21.64,0l81.02,81.173ZM2,18.2A15.3,15.3,0,0,1,17.182,3H292.9a15.192,15.192,0,0,1,15.182,15.2v245.08a15.3,15.3,0,0,1-15.182,15.2H17.182A15.2,15.2,0,0,1,2,263.277ZM93.825,125.433a30.608,30.608,0,1,1,30.608-30.608A30.608,30.608,0,0,1,93.825,125.433Z" transform="translate(28.608 42.912)" fill="#34d399" stroke="#000" stroke-width="0"/>
                    </g>
                  </g>
                </svg>
                <p className='font-bold text-xs text-center text-neutral-400'>Company Banner</p>
              </div>
            </Link>


          </div>

          <div className='py-2 space-y-2 pb-12'>

            <p className='font-bold'>History</p>

            {data?.data?.map(transaction => (
              <Transaction 
                key={transaction._id} 
                {...transaction}
              />
            ))}


          </div>

        </div>

        {/* <div className='bg-gradient-to-tr from-green-400 to-emerald-400 fixed grid place-content-center rounded-full w-12 h-12 shadow-2xl bottom-5 right-5'>
          <BiQrScan
            className="text-2xl font-bold text-white"
          />
        </div> */}

        
      </main>
    </>
  )
}
