import Head from 'next/head'
import Image from 'next/image'

import { SiGoogleplay } from 'react-icons/si'
import { IoBusSharp } from 'react-icons/io5'
import { TbSend, TbHistory } from 'react-icons/tb'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">

        <div className='flex justify-between items-center p-5 backdrop-blur-xl '>

          <p className='font-bold text-3xl font-[Teko]'>luvo</p>

          <div className='flex place-items-center gap-3 bg-black p-3 font-bold !text-white rounded-md active:ring-1 ring-neutral-700'>
            <SiGoogleplay className="text-sm" />
            <span className="text-sm">Download App</span>
          </div>

        </div>



        <div className='grid lg:grid-cols-2 gap-8 items-center p-8 bg-emerald-50'>


          <div className='lg:p-10 space-y-8'>
            <p className='text-5xl font-bold'>
              Your rides are good make their payments better with luvo
            </p>
            <p className=''>
              If you're looking for a great transport payment app, luvo is the perfect choice. With luvo, you can easily and quickly pay for your transport, whether it's a bus, train, or taxi.
            </p>
            <div className='inline-flex place-items-center gap-3 bg-black p-3 font-bold !text-white rounded-md active:ring-1 ring-neutral-700'>
              <SiGoogleplay className="text-sm" />
              <span className="text-sm">Download App</span>
          </div>
          </div>


          <div className='relative h-[500px]'>

            <Image
              className='absolute bottom-5'
              src="/blob.png"
              style={{ objectFit: 'contain', objectPosition: 'center' }}
              width={1000}
              height={1000}
              alt=""
            />

            <Image
              className=''
              src="/woman.png"
              style={{ objectFit: 'contain', objectPosition: 'center' }}
              fill
              alt=""
            />

          </div>


        </div>


        <div className='grid lg:grid-cols-3 gap-12 p-12'>


          <div className='bg-white shadow-2xl p-5 rounded-lg space-y-4'>
            <div className='inline-flex place-items-center p-5 bg-gradient-to-tr from-blue-500 to-green-300 rounded-md'>
              <IoBusSharp className="text-4xl text-white" />
            </div>

            <p className='font-bold text-lg'>10+ Transport services</p>
            <p className=''>Wide range of transport services to pay with the luvo app</p>
          </div>

          <div className='bg-white shadow-2xl p-5 rounded-lg space-y-4'>
            <div className='inline-flex place-items-center p-5 bg-gradient-to-tr from-yellow-500 to-amber-300 rounded-md'>
              <TbSend className="text-4xl text-white" />
            </div>

            <p className='font-bold text-lg'>Fast Payments</p>
            <p className=''>Easy to use app with fast payment system</p>
          </div>

          <div className='bg-white shadow-2xl p-5 rounded-lg space-y-4'>
            <div className='inline-flex place-items-center p-5 bg-gradient-to-tr from-green-500 to-emerald-300 rounded-md'>
              <TbHistory className="text-4xl text-white" />
            </div>

            <p className='font-bold text-lg'>Up to date History</p>
            <p className=''>Check your payment history and track your pendings</p>
          </div>



        </div>
        
      </main>
    </>
  )
}
