import Button from '@/components/Button'
import Input from '@/components/Input'
import fetchData from '@/hooks/fetchData'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useState } from 'react'


export default function Login() {

  const [form, setForm] = useState({ });
  const [loading, setLoading] = useState(false);

  const router = useRouter();

  const handleSubmit = async() => {

    setLoading(true)
    const options = {
      method: 'POST',
      body: form,
    }
    const { data } = await fetchData('/api/login', options);
    if(data) localStorage.setItem('luvo_driver', JSON.stringify(data));

    router.push('/dashboard');

  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-green-400 flex flex-col items-center place-content-center gap-8 p-4">


          <div className='space-y-4'>
            <p className='font-bold text-4xl text-center font-[Teko] text-white'>luvo</p>
            <small className='block text-white text-center'>Driver</small>

            {/* <div className='w-2/3 mx-auto text-center text-xs'>
              Use one our one click login to access your account
            </div> */}
          </div>


          {/* <div className='w-2/3'>
            <div className='flex justify-center items-center gap-3 border-2 border-orange-600 bg-white rounded-full py-3 px-5'>
              <FcGoogle className="" />
              <span className='text-xs font-bold'>Continue with google</span>
            </div>
          </div> */}

          <div className='max-w-md w-5/6 mx-auto bg-white p-10 space-y-4 rounded-lg shadow-xl'>
            <Input
              name="email"
              type="email"
              placeholder="Email"
              onChange={(e) => setForm({ ...form, [e.target.name]: e.target.value })}
            />
            
            <Input
              name="password"
              type="password"
              placeholder="Password"
              onChange={(e) => setForm({ ...form, [e.target.name]: e.target.value })}
            />

            <Button 
              text="Sign In"
              loading={loading}
              onClick={handleSubmit}
            />

            {/* <p className='text-xs text-center'>Don't have an account? <Link className='font-bold text-green-400' href="/register">Sign Up</Link></p> */}

          </div>
        
      </main>
    </>
  )
}
