import Button from '@/components/Button';
import Input from '@/components/Input';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import Script from 'next/script';
import { HiUserCircle } from 'react-icons/hi';
import { useRouter } from 'next/router';
import fetchData from '@/hooks/fetchData';
import toast, { Toaster } from 'react-hot-toast';
import Navbar from '@/components/Navbar';



export default function FundWallet() {

  const router = useRouter();
  const [form, setForm] = useState({ });
  const [loading, setLoading] = useState(false);

  const handleUpdate = async() => {

    setLoading(true);

    const options = {
      method: 'POST',
      body: form,
    }

    const { status, data } = await fetchData('/api/profile', options);
    setLoading(false);

    if(status === 0){
      return router.push('/login');
   }

    if(status === 2){
      toast.success('Profile Updated')
    }

  }

  useEffect(() => {
    (async() => {
      const { user } = await fetchData('/api/user');
      if(user) localStorage.setItem('luvo_driver', JSON.stringify(user));
      setForm({
        fullname: user.fullname,
        email: user.email,
        tag: user.tag,
        company: user.company,
        password: ""
      });
    })();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-md mx-auto h-screen flex flex-col p-4 gap-4 bg-neutral-50">
        <Toaster 
          toastOptions={{
            className: 'text-xs font-semibold',
          }}
        />

        <Navbar 
          text="Profile"
        />

        <div className='bg-white rounded-lg p-5 flex flex-col gap-2 justify-center items-center'>
          <HiUserCircle className="text-[6rem] text-green-400" />
          <p className='font-bold text-xs'>Profile Image</p>
        </div>

        
        <div className='space-y-3 bg-white'>

          <Input
            name="fullname"
            placeholder="Enter Fullname"
            onChange={(e) => setForm({ ...form, [e.target.name]: e.target.value })}
            value={form?.fullname}
            required
          />

          <Input
            name="email"
            placeholder="Enter Email"
            onChange={(e) => setForm({ ...form, [e.target.name]: e.target.value })}
            value={form?.email}
            required
            disabled
          />

          <Input
            name="tag"
            placeholder="tag"
            onChange={(e) => setForm({ ...form, [e.target.name]: e.target.value })}
            value={(form.tag || '').search(/^@/) === 0 ? form.tag || '' : '@'+ (form.tag || '')}
            required
            disabled
          />

          <Input
            name="company"
            placeholder="Transport Company Name"
            onChange={(e) => setForm({ ...form, [e.target.name]: e.target.value })}
            value={form.company}
            required
          />

          <Input
            name="password"
            placeholder="Enter Password"
            onChange={(e) => setForm({ ...form, [e.target.name]: e.target.value })}
            value={form?.password}
            required
          />

          <Button
            text="Update"
            onClick={handleUpdate}
            loading={loading}
          />

        </div>
        
      </main>

      <Script
        src="https://js.paystack.co/v1/inline.js"
        strategy="afterInteractive"
      />
    </>
  )
}
