import Head from 'next/head';

import { RiFileHistoryFill } from 'react-icons/ri';
import Script from 'next/script';
import { useRouter } from 'next/router';
import Link from 'next/link';
import { useEffect, useState } from 'react';


export default function Home() {

  const router = useRouter();
  const [amount, setAmount] = useState(0);

  useEffect(() => setAmount(JSON.parse(localStorage.getItem('ongoing_transc'))?.amount), [])

  return (
    <div>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className="flex justify-center items-center w-full h-screen max-w-md p-5 mx-auto">


        <div className='p-4 py-20 space-y-3'>

            <Script strategy="afterInteractive" src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></Script>
            <lottie-player src="https://assets9.lottiefiles.com/packages/lf20_pqnfmone.json"  background="transparent"  speed="1"  style={{ width: '100px', height: '100px', margin: 'auto' }} loop autoplay></lottie-player>
            
            <p className='text-center text-4xl font-bold'>&#8358; {(amount)?.toLocaleString()}</p>
            <p className='text-center text-xs font-bold'>Transaction Success</p>

            <Link href={`/dashboard`} className='flex justify-center'>
                <p className='inline-flex items-center justify-center gap-2 p-2 px-8 bg-green-400 text-white text-xs rounded-full text-center font-bold'>
                    Go to Dashboard
                </p>
            </Link>

        </div>

      </main>

    </div>
  )
}
