import Button from '@/components/Button';
import Input from '@/components/Input';
import Head from 'next/head';
import { useEffect, useState } from 'react';

import Script from 'next/script';
import { GiMoneyStack } from 'react-icons/gi';
import { useRouter } from 'next/router';
import fetchData from '@/hooks/fetchData';
import Navbar from '@/components/Navbar';
import Select from '@/components/Select';
import { toast, Toaster } from 'react-hot-toast';



export default function Withdraw({ banks }) {

  const router = useRouter();
  const [showConfirm, setShowConfirm] = useState(false);
  const [form, setForm] = useState();

  const [amount, setAmount] = useState();
  const [user, setUser] = useState({});
  const [loading, setLoading] = useState(false);

  const handleBank = (e) => {
    setForm({ ...form, 
      [e.target.name]: e.target.value,
      bank_name: banks.find(bank => bank.code === e.target.value)?.name
    })
  }

  const validateBank = async(e) => {

    if(form.amount > user?.balance){
      return toast.error('Not enough balance');
    }

    setLoading(true);
    const details = { 
      account_number: form?.account_number,
      bank_code: form?.bank_code
    };

    const { status, data } = await fetchData('/api/validate-bank', { method: 'POST', body: details });
    if(status === 2){
      setForm({ ...form, ...data });
      setLoading(false);
      setShowConfirm(true);
      return
    }
    
    return toast.error('Account Number unable to resolve');
  }
  
  const handleWithdrawal = async() =>{
    setLoading(true);
    const { status } = await fetchData('/api/payout', { method: 'POST', body: form });

    if(status === 2){
      setLoading(false);
      localStorage.setItem('ongoing_transc', JSON.stringify(form));
      toast.success('Withdrawal Successful');
      return router.push('/success');
    }
    
    return toast.error('Error sending payment');
    
  }

  useEffect(() => {
    (async() => {
      const { user } = await fetchData('/api/user');
      if(user) localStorage.setItem('luvo_driver', JSON.stringify(user));
      setUser(user);
    })();
  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="max-w-md mx-auto h-screen flex flex-col p-4 gap-4 bg-neutral-50">
        <Toaster 
          toastOptions={{
            className: 'text-xs font-semibold',
          }}
        />


        <Navbar 
          text="Withdraw"
        />

        
        <div className='space-y-3 bg-white'>

          <Select
            name="bank_code"
            placeholder="Choose Bank"
            onChange={handleBank}
            value={form?.bank_code}
            options={banks}
            required
          />

          <Input
            name="account_number"
            placeholder="Account Number"
            onChange={(e) => setForm({ ...form, [e.target.name]: e.target.value })}
            value={form?.account_number}
            required
          />

          <Input
            name="amount"
            placeholder="Amount to be paid"
            onChange={(e) => setForm({ ...form, [e.target.name]: e.target.value.replace(/[^\d]/ig,'') })}
            value={`₦ ${parseInt(form?.amount||0).toLocaleString()}`}
            required
          />

          <Button
            text="Withdraw"
            onClick={validateBank}
            loading={loading}
          />

        </div>


        {showConfirm && <div className='fixed top-0 left-0 w-full h-full bg-black opacity-20' onClick={() => setShowConfirm(false)}></div>}
        <div className={`${!showConfirm ? '-bottom-full' : 'bottom-0'} fixed left-0 w-full h-auto p-6 rounded-t-2xl bg-white space-y-4 py-12 duration-200`}>
          <p className='font-bold text-center'>Withdraw</p>

          <p className="text-3xl font-bold text-center text-green-500">&#8358; {form?.amount?.toLocaleString()}</p>
          <div className='space-y-1'>
            <p className="text-sm text-center uppercase">{form?.account_name}</p>
            <p className="text-sm text-center">{form?.account_number}</p>
            <p className="text-sm text-center">{form?.bank_name}</p>
          </div>



          <Button 
            text="Confirm"
            onClick={handleWithdrawal}
            loading={loading}
          />

        </div>
        
      </main>

      <Script
        src="https://js.paystack.co/v1/inline.js"
        strategy="afterInteractive"
      />
    </>
  )
}


export async function getServerSideProps(context) {

  const { banks } = await fetchData('/api/banks');

  return {
    props: {
      banks: banks || null
    }
  }
}